### ISSUE TITLE
Information on using this SDK with a skygear.io endpoint

### ISSUE THREAD

**Issue by singhnitesh** [SkygearIO/chat-SDK-iOS#8] opened 2016-12-19 11:58 UTC
Hi,
I was exploring Skygear for adding chat to my iOS application and wanted to know if this sdk can directly integrated with Skygear endpoint?
I have signed up for an account, created new application via the portal and configured the example app with endpoint & key. The requests for user login & signup are being successfully executed but when I try to create direct/group conversation, it fails with message "An unexpected error has occurred."
Am I missing something here?

**Comment by chpapa** [comment] 2016-12-20 06:16
@singhnitesh 

Thanks for your interest!

The problem is because the open source Chat Plugins have not been installed on Skygear Commercial Hosting yet, we will have it on portal.skygear.io at around Jan 2017, stay tuned!

Currently there are two ways you can deploy it:

1. Deploy the opensource version, which might be complicated...

2. You can deploy it to portal.skygear.io via Cloud Code.

For option 2, you may open an account on portal.skygear.io, go to info and copy your Cloud Code Git URL (let's say it is ssh://git@git.skygeario.com/demo.git), and run the following code.

```
git clone https://github.com/rickmak/chatdemo.git
git remote add skygear ssh://git@git.skygeario.com/demo.git
git push skygear
```
After that you should be able to use the latest Skygear Chat client.

You may reference to the following for API doc and Demo of Skygear Chat:

### iOS SDK
* Repo: https://github.com/SkygearIO/chat-SDK-iOS
* Doc: http://cocoadocs.org/docsets/SKYKitChat/0.0.1/Classes/SKYChatExtension.html
* Example: https://github.com/SkygearIO/chat-SDK-iOS/tree/master/Example
* Demo: https://github.com/skygear-demo/swift-chat-demo

### Android SDK
* Repo: https://github.com/SkygearIO/chat-SDK-Android
* Doc: https://docs.skygear.io/android/plugins/chat/reference/
* Example: https://github.com/SkygearIO/chat-SDK-Android/tree/master/chat_example

### JS SDK
* Repo: https://github.com/SkygearIO/chat-SDK-JS
* Doc: https://doc.esdoc.org/github.com/skygeario/chat-SDK-JS/
* Example: https://github.com/SkygearIO/chat-SDK-JS/tree/master/demo

Feel free to send us further question at https://groups.google.com/forum/#!forum/skygear-user-group

I'm closing this issue first :)

**Closed as completed by chpapa** 2016-12-20 06:16 UTC
